### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/earthkit#16]
### What happened?

The documentation states that we have an earthkit recipe but it doesn't seem to exist:
https://earthkit.readthedocs.io/en/latest/install.html

### What are the steps to reproduce the bug?

Either upload an earthkit recipe or remove this approach from the documentation.

### Version

latest

### Platform (OS and architecture)

-

**Comment by sandorkertesz** [comment]
Documentation has been updated.
